### PR TITLE
Add XMM-Newton RGS spectra

### PR DESCRIPTION
**Pull request by jdeplaa**
These XMM-Newton RGS1 and RGS2 spectra of Mrk 421 were taken for calibration purposes. Mrk 421 is an AGN which shows a variable absorbed powerlaw spectrum.

RGS response matrices are already multiplied by the effective area, so no ARF files are generated in the XMM SAS software.

Note that these files are ordered in wavelength instead of energy, which is different from the usual OGIP files.

### CODE REVIEW

**Comment by hamogu** [comment]
I wonder if we need RGS1 and 2, or if we can save ourselves 30 MB and just use one of them? File formats are the same anyway, but it might be good to have both for tests that read in both and fit them together. 

I'm not sure what's best and I'm happy to merge as is - I just wanted to bring it up to make sure we consciously decide that's what we do and don't simply default to both because we have both.

**Comment by jdeplaa** [comment]
Yes, we could limit it to RGS1 files. There are of course some differences in the data (missing CCDs and bad columns), but not in the spectral format. I have removed RGS2 in commit [83d1408](https://github.com/HEACIT/curated-test-data/pull/3/commits/83d1408bc579364fbc27bca6eb3f008eca5d77ed). You can choose which version you would like best. 

Since this is a powerlaw spectrum, fitting simultaneously is not critical for the result. This would be different for line spectra where some important lines would be missing due to the failed CCD. So, I think we can skip the RGS2 spectrum in this case. It can always be added upon request as the files are in the repository already.

**Comment by hamogu** [comment]
Can you quash the commits with the rebase (`git rebase -i HEAD~2`)? Otherwise, we still have both files in the git repro in the intermediate commit. If our goal is to keep the file size of the repro down, we need to squash the commit so we don't have "file added, then file removed", since git keeps the complete history - including files that were removed later.

**Comment by jdeplaa** [comment]
Yes, the squash should be done now in [21533fd](https://github.com/HEACIT/curated-test-data/pull/3/commits/21533fde54386583140e7875febf8efe070896ed).

**Comment by hamogu** [comment]
I still see two separate commit where the first one add the files that are then removed again in the second: https://github.com/HEACIT/curated-test-data/pull/3/commits/a0ae3d3885ccbb2cf001e74cf3ebe076ec621da1
I'll check out that branch and do that locally before I merge to main.

**Comment by jdeplaa** [comment]
Yes, I see it too. Git suggested that the commits were merged, but apparently not in the way I intended... If you can do the squash, please do it.

**Comment by hamogu** [comment]
Thanks!

**Pull request merged**
